name: Release Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Upload Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o quote-scraper-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload binary to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: quote-scraper-${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}